name: Development - CI
on:
  push:

jobs: 
  what_changed_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: changed_files
      run: EXPECTED_SHA=a737275d9fbd1b795f8ee8b6a7da0a03f6721fb5 DOCKER_IMAGE_SHA=$(git --no-pager log -1 --format=format:%H -- src/fake/) node test.js
