name: Development - CI
on:
  push:

jobs: 
  what_changed_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Check main SHA
      run: |
        CHANGES=$(git --no-pager log -1 --format=format:%H  HEAD^..HEAD --name-only -- test.yaml | head -n1)
        echo $CHANGES
        x=$(git rev-parse HEAD)
        echo "commit sha" $x

        if [ "${CHANGES}" == "${x}"  ]; then
          echo "true"
        else
          echo "false"
        fi
    - name: changed_files
      run: EXPECTED_SHA=f785e30 DOCKER_IMAGE_SHA=$(git --no-pager log -1 --format=format:%h -- src/fake/) node test.js

