name: Development - CI
on:
  push:

jobs: 
  what_changed_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: changed_files
      run: EXPECTED_SHA=b8b67628d544ae6bef877c965ef244df33c58ff9 DOCKER_IMAGE_SHA=$(git --no-pager log -1 --format=format:%H -- src/fake/) node test.js
