name: Development - CI
on:
  push:

jobs: 
  what_changed_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: changed_files
      id: changed_files
      run: |
          last_commit=$(git --no-pager log -1 --format=format:%H  HEAD^..HEAD --name-only | tr '\n' ' ' )
          last_commit2=$(git --no-pager log -2 --format=format:%H  HEAD^..HEAD --name-only | tr '\n' ' ' )
          echo --- last commit 1 ---
          echo $last_commit
          echo --- last commit 2 ---
          echo $last_commit2
